#!/usr/bin/env python3
"""
zai_chat — browser-backed completion for Z.ai. chat.z.ai gates every completion
behind an interactive slider captcha + risk engine; the captcha token is bound to
the solving browser's fingerprint and cannot be replayed over pure HTTP (verified),
and the SPA withholds `/api/v2/chat/completions` until the slider is solved.
So `zai chat` drives the logged-in persistent-profile browser, submits the message
in the real composer, detects the security-verification slider, waits for the user
to solve it in the headed window, then returns the assistant's rendered reply.
This is the single browser touchpoint in the zai CLI.
"""
import json, sys, time, os
from pathlib import Path

OUT_DIR = Path.home() / ".zai-cli" / "out"
OUT_DIR.mkdir(parents=True, exist_ok=True)
CHROME = {"Deep Think", "Max", "Sign in", "AI PPT", "New Chat", "Meet Your AI Agents",
          "Code faster with ZCode. Automate more with AutoClaw.", "ZCode", "AutoClaw",
          "Chat", "Agent", "Share", "Thought Process", "Please complete security verification",
          "Generated by AI. For reference only.", "Tech Blog", "Contact us",
          "Terms of Service", "Privacy Policy"}


def run(prompt, model="x-preview-l", no_think=False, effort="max", token="", profile=None):
    profile = profile or Path.home() / ".zai-cli" / "login-profile"
    if not prompt.strip():
        return {"ok": False, "err": "no-prompt", "msg": "Usage: zai chat '<prompt>'"}

    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        try:
            ctx = p.chromium.launch_persistent_context(
                str(profile), headless=False,
                args=["--no-sandbox", "--disable-blink-features=AutomationControlled"],
                viewport={"width": 1280, "height": 900})
        except Exception as e:
            return {"ok": False, "err": "launch-failed", "msg": str(e)}
        page = ctx.pages[0] if ctx.pages else ctx.new_page()
        page.goto("https://chat.z.ai/", wait_until="domcontentloaded", timeout=60000)
        for _ in range(30):
            if page.locator("#chat-input").count() > 0:
                break
            time.sleep(1)
        page.click("#chat-input")
        page.keyboard.type(prompt, delay=12)
        page.keyboard.press("Enter")

        # Wait for the reply, handling the security-verification slider that appears.
        start = time.time()
        deadline = start + 420   # up to 7 min (thumbnails w/ max-effort thinking can be slow)
        warned = False
        best = ""
        stable = 0
        saw_processing = False
        while time.time() < deadline:
            time.sleep(2)
            state = page.evaluate("""() => {
                const t = document.body.innerText || '';
                const verif = /complete security verification|drag the slider|verify you are human|滑块|安全验证/i.test(t);
                const dots = /^\\.\\.\\.$/.test(Array.from(document.querySelectorAll('*'))
                    .filter(e=>e.children.length===0).map(e=>e.textContent.trim()).filter(Boolean).join('|'));
                return {verif, t};
            }""") if not page.is_closed() else {"verif": False, "t": ""}
            if state["verif"]:
                if not warned:
                    warned = True
                    print(">> Security verification required: drag the slider in the browser window to continue. Waiting...", flush=True)
                time.sleep(1)
                continue
            # No captcha: extract assistant markdown blocks (exclude the user's own prompt)
            answer = extract(page, prompt)
            if answer and len(answer) > len(best):
                best = answer
                stable = 0
            else:
                stable += 1
            if best and stable >= 6:
                break
            # stop early once a non-trivial answer is stable (thinking done)
            if best and len(best) > 40 and "…" not in best[-5:] and time.time() - start > 30:
                pass
        body = page.evaluate("() => document.body.innerText") if not page.is_closed() else ""
        try: ctx.close()
        except: pass

        answer = best or extract_from_body(body, prompt)
        ok = bool(answer and answer.strip() and answer.strip() != prompt.strip())
        f = OUT_DIR / f"chat-{int(time.time())}.json"
        f.write_text(json.dumps({"prompt": prompt, "model": model, "answer": answer,
                                 "waited_s": round(time.time()-start), "body": body[-3500:]}))
        return {"ok": ok, "f": str(f), "model": model, "chars": len(answer), "answer": answer}


def extract(page, prompt):
    """Pull assistant markdown blocks, excluding the user's own prompt and chrome."""
    try:
        mds = page.evaluate("""() => {
            const out=[];
            document.querySelectorAll('[class*="markdown"], main [class*="content-block"], [class*="assistant"] [class*="text"]').forEach(el=>{
                const t=(el.innerText||'').trim(); if(t) out.push({tag:el.tagName, cls:String(el.className).slice(0,40), t});
            });
            return out;
        }""")
    except Exception:
        return ""
    cands = []
    for m in (mds or []):
        t = m["t"]
        if t == prompt.strip():
            continue
        lines = [l for l in t.splitlines() if l.strip() not in CHROME and l.strip() != ""]
        cleaned = "\n".join(lines).strip()
        if cleaned and cleaned.strip() not in ("Thought Process",):
            cands.append(cleaned)
    if not cands:
        return ""
    cands.sort(key=len)
    return cands[-1]


def extract_from_body(body, prompt):
    idx = body.rfind(prompt)
    tail = body[idx + len(prompt):] if idx >= 0 else body
    out, skip = [], False
    for ln in tail.splitlines():
        s = ln.strip()
        if s == "Thought Process":
            continue
        if s == "Deep Think" or s == "Max" or s in CHROME or s == "":
            continue
        if s in ("Regenerate", "Copy", "Share") or s.startswith("GPT-4") or s.startswith("GLM"):
            continue
        out.append(ln)
    return "\n".join(out).strip()


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("prompt", nargs="?")
    ap.add_argument("--model", default="x-preview-l")
    ap.add_argument("--effort", default="max")
    ap.add_argument("--no-think", action="store_true")
    a = ap.parse_args()
    print(json.dumps(run(a.prompt, model=a.model, no_think=a.no_think, effort=a.effort)))
